### ISSUE TITLE
Problem training SBERT and SBERT DA to reproduce results

### ISSUE THREAD

**Issue by dhvalden** [ucinlp/covid19-backend#61]
I'm having problems to run the training scripts related to SBERT and SBERT DA. 

My setup is:
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009

Steps to reproduce:

1.- After cloning and installing successfully run:
python3 scripts/ml/train_nli.py --model-name digitalepidemiologylab/covid-twitter-bert --batch_size=10 --epochs=10 --lr=5e-5 --accumulation_steps 32 --train data/multinli_1.0/multinli_1.0_train.jsonl --dev data/multinli_1.0/multinli_1.0_dev_matched.jsonl --ckpt my_model

The error message is:
Traceback (most recent call last):
  File "scripts/ml/train_nli.py", line 17, in <module>
    from backend.ml.sentence_bert import SentenceBertClassifier
  File "/nobackup/ptdhv/covid19-backend/backend/ml/sentence_bert.py", line 34, in <module>
    class SentenceBertBase(Detector, torch.nn.Module):
  File "/nobackup/ptdhv/covid19-backend/backend/ml/sentence_bert.py", line 50, in SentenceBertBase
    loss_kwargs: Dict[str, Any] = None) -> torch.FloatTensor:
  File "/home/home01/ptdhv/.local/lib/python3.7/site-packages/overrides/overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/home/home01/ptdhv/.local/lib/python3.7/site-packages/overrides/overrides.py", line 114, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/home/home01/ptdhv/.local/lib/python3.7/site-packages/overrides/overrides.py", line 135, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/home/home01/ptdhv/.local/lib/python3.7/site-packages/overrides/signature.py", line 93, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "/home/home01/ptdhv/.local/lib/python3.7/site-packages/overrides/signature.py", line 288, in ensure_return_type_compatibility
    f"{method_name}: return type `{sub_return}` is not a `{super_return}`."
TypeError: SentenceBertBase.forward: return type `<class 'torch.FloatTensor'>` is not a `<class 'NoneType'>`.

**Comment by rloganiv** [comment]
Whoops! Looks like the latest version of `overrides` is actually doing something at runtime.
