### ISSUE TITLE
Problems reproducing results of BiLSTM

### ISSUE THREAD

**Issue by dhvalden** [ucinlp/covid19-backend#62]
Training under Linux CentOS, on Nvidia Tesla V100, Cuda version 10.1, on correctly built repo and under the recommended conda environment.

Steps to reproduce: 

1.- run: `python3 -m scripts.ml.train_bilstm --train data/multinli_1.0/multinli_1.0_train.jsonl --dev data/multinli_1.0/multinli_1.0_dev_matched.jsonl --output-dir /covid19-backend/models/ --epochs 20`

Error Message: 
Traceback (most recent call last):
  File "/apps/developers/compilers/anaconda/2019.10/1/default/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/apps/developers/compilers/anaconda/2019.10/1/default/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nobackup/ptdhv/covid19-backend/scripts/ml/train_bilstm.py", line 164, in <module>
    main()
  File "/nobackup/ptdhv/covid19-backend/scripts/ml/train_bilstm.py", line 120, in main
    acc = accuracy(predictions, labels)
  File "/nobackup/ptdhv/covid19-backend/scripts/ml/train_bilstm.py", line 40, in accuracy
    return correct.sum() / length
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by tamannahossainkay** [comment]
Thanks for catching this issue. I've updated the script so that tensors in the accuracy function are on the same device.
